services:

  frontend:
    build: ./frontend
    container_name: devops-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: devops-backend
    ports:
      - "5000:5000"